human_scene_interaction: false
human_human_interaction: false
looping: false
keyjoints:
  - pelvis
  - spine3
  - right_wrist
  - left_wrist
  - right_foot
  - left_foot
matching_features:
  - keyjoints
motions:
  - dataset: amass
    motion_file: GRAB/s1/banana_pick_all_stageii.npz
    start_frame: 0
    end_frame: 2162
    match_start_frame: 176
    match_end_frame: 206
